### ISSUE TITLE
Still encountering random crashes

### ISSUE THREAD

**Issue by VL437** [CookiePLMonster/SilentPatchBully#23] opened 2018-07-14 21:20 UTC
The game appeared more stable with your patch, but the deeper I progressed the more random crashes I started to encountered. I've joined all my dumps hoping it can help.

[Bully.exe.20180708174259.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2195267/Bully.exe.20180708174259.zip)
[Bully.exe.20180713203331.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2195265/Bully.exe.20180713203331.zip)
[Bully.exe.20180713203631.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2195264/Bully.exe.20180713203631.zip)
[Bully.exe.20180714162426.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2195262/Bully.exe.20180714162426.zip)
[Bully.exe.20180714165256.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2195260/Bully.exe.20180714165256.zip)

Here's where I remember encountering each of them.
1) During Chapter 1 mission "Help Gary" while fighting bullies in the school's bus/bike garage area
2) While biking in that same area, as I was about to leave school grounds (Chapter 2, not in a mission)
3) While simply walking in that same area again, I had prefects running after me (again, Chapter 2, a in any mission)
4) During the intro cutscene of Chapter 3 mission "Miracle on Bullworth St."
5) While being in the Dragon's Wing Comics shop basement (Chapter 3, not in any mission)

**Comment by CookiePLMonster** [comment] 2018-07-22 21:21
Build 2 is now out! I do not know if this specific crashes have been fixed, though - but it's still worth a test!

**Comment by VL437** [comment] 2018-07-22 21:39
Thanks for the notice! I'll test and let you know if I'm still getting any issues.

**Comment by VL437** [comment] 2018-07-22 21:55
Nope :( Already got a new crash after not even 5 minutes...

For the 4th time, it happened on the right side of the school, as I was leaving the parking area. I was walking toward the school right after completing "A Little Help IV". I don't know whether these are just coincidences or there really is something up with that specific area...

Anyway, here's the dump: [Bully.exe.20180722174641.dmp.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2217438/Bully.exe.20180722174641.dmp.zip)

**Comment by VL437** [comment] 2018-07-22 23:42
Here's my save file: [BullyFile1.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2217498/BullyFile1.zip)

My settings are:
Resolution = 1366 x 768
Anti Aliasing = Off
VSync = On
Shadows = Off

I'm playing on the steam version (1.200 SP Build 2) on Windows 10 (no compatibility mode) without any mod. My processor spec is "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz, 2712 Mhz, 2 Core(s), 4 Logical Processor(s)" (no graphic card).

I attempted to reproduce the crash 3 times by following the same route than in my previous message, but was only able to reproduce it once. Not sure if there's really a consistent way to reproduce it... Here the route (last save was done at nerd's hideout):

1) I went out by the main exit (by going through the store) (I didn't interact with any of the nerds, but I stopped to listen to what they were saying).
2) I ran to the nearest bus stop (just a bit to the north of the nerd's hideout) and took the bus.
3) Once at school, I ran to the "A little help IV" mission (I stopped in front of the school to listen to what NPCs were saying/doing, but again, I didn't interact with any of them).
4) I beat mission "A little help IV".
5) I attempted to walk back to the front of the school. This is where the crashes happened. On my previous message, it occurred right when I left the packing. This time, after leaving the parking, I stopped to watch a fight that was going on (no interaction, again) and then it crashed as I was walking under the arch separating the school's front from its right side.

Here's the dump if it can help: [Bully.exe.20180722184610.dmp.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2217510/Bully.exe.20180722184610.dmp.zip)

**Comment by CookiePLMonster** [comment] 2018-07-23 07:47
You have shadows disabled - can you try enabling them? I am not 100%
certain but I think your first crash traced back to some function related
to shadows.

**Comment by VL437** [comment] 2018-07-23 10:20
I'm away from home and won't have access to the game until next weekend, but I'll try that once I'm back.

I believe I had shadows enabled at some point (for the first 4 crashes of my original message), but disabled them after reading forum comments stating it seems to make the game more stable.

**Comment by CookiePLMonster** [comment] 2018-07-23 23:02
Miraculously, I once crashed at the same address now! I saved a full dump from this event so hopefully something can be read from that...

I then attempted exact same steps again and did not reproduce it - so as far as user actions go, it feels totally random.

**Comment by VL437** [comment] 2018-11-18 03:57
Not sure if you're still working on the patch, but I've almost reached 100% completion at this point and I thought I'd share my observations:

- The game started crashing a lot at chapter 3 (that's when I created this issue).
- It got a lot more stable once I reached chapter 4 (still few crashes here and there, but nothing compared to chapter 3).
- It got very unstable again by the end of chapter 5 (this started when I unlocked "Complete Mayhem").
- It never crashed since I've reached chapter 6 (and I've spent many hours in it).

I don't know if any conclusion can be drawn from those, but I hope it can help.

**Comment by CookiePLMonster** [comment] 2020-03-07 18:26
Build 3 is now out. What I dubbed above as "this crash everybody has but I've been unable to reproduce" **should** be fixed now so I am going to close this. If you're still encountering crashes with Build 3, go ahead and reopen this issue.

**Closed by CookiePLMonster** 2020-03-07 18:26 UTC
